channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - .
    - breathe
    - cmake
    - colored
    - furo
    - gym
    - jupyter
    - m2r2
    - matplotlib
    - mypy
    - nevergrad
    - ninja
    - opencv-python
    - Pillow
    - pybind11
    - pyproj
    - setuptools
    - sphinx
    - sphinx-automodapi
    - torch
    - torchvision
    - variables-info
    - wheel
    - xmltodict
