dependencies:
  - python==3.9.18
  - pip==23.3
  - pip:
    - .
    - breathe==4.35.0
    - cmake==3.27.7
    - colored==2.2.3
    - furo==2023.9.10
    - jupyter==1.0.0
    - m2r2==0.3.3.post2
    - mypy==1.6.1
    - ninja==1.11.1.1
    - pybind11==2.11.1
    - sphinx-automodapi==0.16.0
    - sphinx-basic-ng==1.0.0b2
    - xmltodict==0.13.0
