#!/usr/bin/env fish

# Set the directory paths for the project and its includes
set build_dir (pwd)"/build/tests"
set c_implementation_cec_transformations_folder (pwd)"/build/tests/input_data"
set external_dir (pwd)"/external"
set include_dir (pwd)"/include"
set ioh_cec_transformations_folder (pwd)"/static/cec_transformations"
set tests_dir (pwd)"/tests/cpp"

true

for line in (cat .env)
  set -x (echo $line | cut -d '=' -f 1) (echo $line | cut -d '=' -f 2-)
end

cd $build_dir

and rm -f ./test.log

and c++ -Wall -Wextra -pedantic -std=c++17 -lstdc++fs \
  -I$include_dir \
  -I$tests_dir \
  -I$external_dir/fmt/include \
  -I$external_dir/clutchlog \
  -I$external_dir/json/include \
  -isystem $external_dir/googletest/googletest/include \
  -isystem $external_dir/googletest/googletest \
  $tests_dir/problem/distorted_onemax_test.cpp \
  -o distorted_onemax_test \
  $build_dir/../lib/libgtest.a -lpthread

and rm -f $c_implementation_cec_transformations_folder
and ln -s $ioh_cec_transformations_folder $c_implementation_cec_transformations_folder

and ./distorted_onemax_test
