name: Windows

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug


jobs:
  build-test-python:
    runs-on: windows-2022
    strategy:
      matrix:
        python-version: ["3.9.x"]
        architecture: [x86]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true    

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        detached: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
        architecture: ${{matrix.architecture}}
    - name: Install library
      run: |
        python -m pip install --upgrade pip
        pip install mypy xmltodict wheel
        pip install -e . -v
    - name: Run unit tests
      run: python -m unittest -v
